### PR TITLE
Return ruleSet.getSelectors() as list from array

### PR DESCRIPTION
**Pull request by xaoseric**
This returns the ruleSet.getSelectors() array as a list sense the update that made it return an array.

### CODE REVIEW

**Comment by hrj** [comment]
Thanks for the PR. I am little out of touch with this code. Will review it sometime this week.

@chetankothari is the main author of this. Chetan, if you have any comments, please let us know.

**Comment by hrj** [comment]
@xaoseric Can you please provide the JS that triggers this? It will help me quickly get into context.

**Comment by xaoseric** [comment]
You changed it from a list to an array awhile back, so the Array.aslist that I added in fixes the issue with returning CombinedSelector[] instead of List<CombinedSelector>, you can see the code that triggers it below, IntelliJ highlighted it as an error so that's how I found it as I'm working on merging the cobra rendering stuff into its own package org.cobraparser. 

https://github.com/radkovo/jStyleParser/commit/4bbce63eb24d7c5becef5d31d3ad586fdbf7e3cf

**Comment by hrj** [comment]
@xaoseric Thanks!

**Comment by hrj** [comment]
@xaoseric FYI, I have fixed some more build errors and pushed to master.

**Pull request merged**
